### ISSUE TITLE
Complete example for "Improving container disk performance"

### ISSUE THREAD

**Issue by Wilhelmsson177** [microsoft/vscode-remote-try-node#11]
I tried out your example on "Improving container disk performance" to improve the npm install process by using a named volume. Unfortunately I'm not able to get it to work it is always mounting the local folder. Can you ad a full example of the Dockerfile and the devcontainer.json?

**Comment by Chuxel** [comment]
@Wilhelmsson177 The Dockerfile is identical to the one shown here.  The added devcontainer.json content is :

```
"mounts": [
    "source=try-node-node_modules,target=${containerWorkspaceFolder}/node_modules,type=volume"
],
"postCreateCommand": "sudo chown node node_modules"
```

So...

```
{
    "name": "Node.js Sample",
    "dockerFile": "Dockerfile",
    "settings": {
        "terminal.integrated.shell.linux": "/bin/bash"
    },
    "extensions": [
        "dbaeumer.vscode-eslint"
    ],
    "forwardPorts": [3000],
    "mounts": [
        "source=try-node-node_modules,target=${containerWorkspaceFolder}/node_modules,type=volume"
    ],
    "postCreateCommand": "sudo chown node node_modules && yarn install"
    "remoteUser": "node"
}
```

Be sure to rebuild the container if it already exists.  This only takes effect when the container is initially created.

You can tell it is setup right by going and looking at the container details in the Remote Explorer.  Under details for the container you should see two mounts:

![image](https://user-images.githubusercontent.com/312252/83213640-7d7ec080-a117-11ea-9e62-480677f68c99.png)

**However**, if you delete the `node_modules` folder, it may loose its connection to the volume.  So, don't `rm -rf` the folder.

The only time this may not happen is if you used the "Try" or "Open Repo in Container" flows since these use volumes by default.

**Comment by Wilhelmsson177** [comment]
Thank you for the fast reply. It is working now. The hint with the Remote Explorer is pure gold.
