### ISSUE TITLE
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by GitHubChrischen** [microsoft/vscode-remote-try-node#26]
Help!!!
I want to connect host server from public network， and meet this problem

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Chuxel** [comment]
If this is related to Codespaces, please raise this [here](https://github.com/github/feedback/discussions/categories/codespaces-feedback) as there is now the ability to right click on the ports view and specify that something should be available publicly.

Port forwarding in Remote - Containers binds to localhost for security reasons, so you would not be able to hit it from another machine.  If you're looking to collaborate with others, check out the Live Share extension. Otherwise you can raise a feature request at https://github.com/microsoft/vscode-remote-release if none of these meet your need.
