### ISSUE TITLE
Error on Raspberry Pi 4 Ubuntu Desktop 21.04 arm64

### ISSUE THREAD

**Issue by rafrafek** [microsoft/vscode-remote-try-node#28]
Template does not work on my Raspberry Pi 4 8GB on Ubuntu Desktop 21.04 arm64.
Both VS Code and Docker run on the same Raspberry. I'm using Remote - Containers extension.
There is info on line 3362:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
Full log from VS Code attached:
[remoteContainers-2021-06-01T16-24-26.100Z.log](https://github.com/microsoft/vscode-remote-try-node/files/6577776/remoteContainers-2021-06-01T16-24-26.100Z.log)

**Comment by Chuxel** [comment]
This is due to the image only being available for x86.  See https://github.com/microsoft/vscode-dev-containers/issues/558

You can build from scratch instead of using the image by copying the contents of [.devcontainer from here](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/javascript-node/.devcontainer) and updating devcontainer.json to reference `base.Dockerfile` instead of` Dockerfile`.
