### ISSUE TITLE
Cache package manager for speed up downloading node_modules

### ISSUE THREAD

**Issue by felinto-dev** [microsoft/vscode-remote-try-node#48]
Hey there!

I would some way to share package manager cache between Host (Windows) and a NodeJS dev container.

I tried using pnpm but fails because is not possible to link packages in node_modules in different disks.
Any opinion about yarn ou npm maybe? I think it can speed up the process for downloading node_modules and save disk space as well.

**Comment by RKsteve** [comment]
MAYBE BUT NO IDEA :D

**Comment by Chuxel** [comment]
@felinto-dev I suspect it will be faster to use Clone Repository in Container Volume and not use any local Windows disk. Alternatively, if you store your source code or npm modules in WSL, things will be faster. This is then linux-to-linux, so you are less likely to encounter issues. That said, you are likely experiencing overhead due to the inefficiency of translating between NTFS and the Linux filesystem rather than transfer times from what I've seen historically.
